services:
  - type: web
    name: cse340-practice
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        scope: run
      - key: USE_SSL
        value: "true"
      - key: SESSION_SECRET
        scope: run